import Joi from "joi";

export const pendingIssueSchema = Joi.object({
  id: Joi.string()
    .guid({ version: "uuidv4" })
    .optional(), // auto-generated by DB

  issue_id: Joi.string()
    .guid({ version: "uuidv4" })
    .required(), // must reference issues(id)

  user_id: Joi.string()
    .guid({ version: "uuidv4" })
    .required(), // must reference users(id)

  technician_id: Joi.string()
    .guid({ version: "uuidv4" })
    .required(), // must reference technicians(id)

  created_at: Joi.date().optional(), // default now()
  updated_at: Joi.date().optional()  // default now()
});
